#!/bin/sh
killall compton
feh --bg-fill ~/Pictures/wallpaper.jpg &
compton --config ~/.config/compton/compton.conf -b 

bspc monitor -d      

~/.config/lemonbar/lemonstart &

bspc config border_width         3
bspc config window_gap          4

bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspwm color config
bspc config focused_border_color "#2059cf"
bspc config normal_border_color "#202080"
