#!/bin/sh
killall compton
killall cleanfullscreen

feh --bg-fill ~/Pictures/wallpaper.jpg &
compton --config ~/.config/compton/compton.conf -b

bspc monitor LVDS1 -d      

~/.config/lemonbar/lemonstart &
~/.config/bspwm/bin/cleanfullscreen &

bspc config border_width        0
bspc config window_gap          4

bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

#bspwm color config
bspc config focused_border_color "#2059cf"
bspc config normal_border_color "#202080"
