#!/bin/sh
pkill picom
pkill cleanfullscreen

sxhkd &
feh --bg-fill ~/.dotfiles/config/.wp.jpg &
picom --config ~/.config/compton/compton.conf -b

bspc monitor LVDS1 -d 1 2 3 4 5 6

xinput set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1

#~/.config/lemonbar/lemonstart &
~/.config/polybar/launch.sh  &
~/.config/bspwm/bin/cleanfullscreen &

bspc config border_width        2
bspc config window_gap          10

bspc config borderless_monocle   true
bspc config focus_follows_pointer true
bspc config split_ratio 0.5

#bspwm color config
bspc config focused_border_color "#6C569C"
bspc config normal_border_color "#333333"
