#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

userresources=$HOME/.config/X11/Xresources

xrdb "$userresources"
xsetroot -cursor_name left_ptr

# custom scripts
~/.local/bin/idletime 180000&

# start program on initialize x
mpd &
dunst &
sxhkd &

# exec window manager
exec bspwm 
