unbind C-b
set-option -g prefix C-a

# Theme PLugin
run-shell "~/.tmux/themes/onedark-tmux/tmux-onedark-theme.tmux"

# OneDark Widget
set -g @onedark_widgets "$USER"

set -g default-terminal "screen-256color"
set -g focus-events on
set-option -sg escape-time 10

bind r source-file ~/.tmux.conf
bind K kill-server
# set -g mouse on

# move window
bind Right next-window
bind Left previous-window
