#!/bin/sh
killall lemonbar
# killall pactl
# killall nmcli

PANEL_WM_NAME=LemonBar


~/.config/lemonbar/lemonconfig | lemonbar -p -B "#af000000" -u 3 -g 1366x20+0+0 -U "#2059cf" -f "3270Narrow Nerd Font" -n $PANEL_WM_NAME

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo lower "$wid"

