#############################
#         Colors            #
#############################

[colors]
background = #F2E7C4
foreground = #F2E1AC
background2 = #6C568C
background3 = #6C569C
danger = #BF3F3F
panel_bg = #0A0E1400

