#############################
#         Colors            #
#############################

[colors]
background = #0E3A73
foreground = #82778C
background2 = #112E50
background3 = #112E40
danger = #8D63fA
panel_bg = #0A0E1400

