[global/wm]
screenchange-reload = true
include-file = ~/.dotfiles/config/polybar/modules.ini
include-file = ~/.dotfiles/config/polybar/colors.ini

[bar/mybar]
# font settings
font-0 = "3270Narrow Nerd Font:size=12;3"

# panel setup
width = 100%
height = 16px
line-size = 3px
offset-x = 0
offset-y = 0
wm-restack = 
background = ${colors.panel_bg}
foreground = ${colors.foreground}
separator = ""
enable-ipc = true

# modules position 
modules-left = bspwm i3 title
modules-right = pulseaudio temperature memory network battery date
