####################################################
#                    Modules                       #
####################################################

[module/bspwm]
type = internal/bspwm
inline-mode = false

label-empty = " %name% "
label-empty-background = ${colors.background2}

label-focused = " %name% "
label-focused-foreground = ${colors.background2}
label-focused-background = ${colors.foreground}

label-urgent = " %name% "
label-urgent-foreground = ${colors.danger}
label-urgent-background = ${colors.background}

label-occupied = " %name% "
label-occupied-foreground = ${colors.background2}
label-occupied-background = ${colors.background}

[module/i3]
type = internal/i3

label-focused = " %name% "
label-focused-foreground = ${colors.background2}
label-focused-background = ${colors.foreground}

label-unfocused = " %name% "
label-unfocused-foreground = ${colors.foreground}
label-unfocused-background = ${colors.background2}

[module/date]
type = internal/date
date = "   %Y-%m-%d "
label-background = ${colors.background3}

date-alt = "   %H:%M "
label-alt-background = ${colors.background3}

[module/battery]
type = internal/battery
battery = BAT0

label-discharging = "%percentage%% "
label-charging = "%percentage%% "
label-full = "%percentage%% "

animation-charging-0 = "  "
animation-charging-1 = "  "
animation-charging-2 = "  "
animation-charging-3 = "  "
animation-charging-4 = "  "

ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "  "

format-full = <ramp-capacity> <label-full>
format-full-background = ${colors.background2}

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.background2}

format-charging = <animation-charging> <label-charging>
format-charging-background = ${colors.background2}

[module/memory]
type = internal/memory
label = "   %percentage_used% % "
label-background = ${colors.background2}

[module/network]
type = internal/network
interface = wlp3s0

label-connected = "%{A:networkmanager_dmenu&:} 直  %essid% %{A}"
label-connected-background = ${colors.background3}
label-disconnected = "%{A:networkmanager_dmenu&:} 睊  Disconnected %{A}"
label-disconnected-background = ${colors.background3}

[module/temperature]
type = internal/temperature

label = "  %temperature-c% "
warn-temperature = 60
label-background = ${colors.background3}

label-warn = "  %temperature-c% "
label-warn-foreground = ${colors.danger}
label-warn-background = ${colors.background3}

[module/pulseaudio]
type = internal/pulseaudio
label-volume = "%percentage%% "
label-muted = " ﱝ muted "
label-muted-foreground = #666
label-muted-background = ${colors.background2}

ramp-volume-0 = " 奄"
ramp-volume-1 = " 奔"
ramp-volume-2 = " 墳"

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${colors.background2}

[module/title]
type = custom/script
exec = "~/.dotfiles/config/polybar/script/window.sh"
label-background = ${colors.background3}
interval = 0.5

